spring:
  profiles:
    active: local

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: ${JWT_SECRET:c2VjcmV0a2V5Zm9yZGV2ZW52aXJvbm1lbnRzZWNyZXRrZXlmb3JkZXZlbnZpcm9ubWVudA==}  # Base64 인코딩된 문자열
  accessTokenValidityInMilliseconds: 3600000
  refreshTokenValidityInMilliseconds: 604800000
  appTokenValidityInMilliseconds: 2592000000

logging:
  level:
    root: info
    com.forrrest: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8080