spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=UTC
    username: root
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  expiration: 1800000 # 30 minutes in milliseconds
  issuer: your-auth-service

server:
  port: 8443
  ssl:
    enabled: false # 기본적으로 비활성화, 환경별 설정에서 활성화
