spring:
  profiles: stag
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/auth_db?useSSL=false&serverTimezone=UTC
    username: root
    password: stagpassword

server:
  ssl:
    enabled: true
    key-store: classpath:keystore/authservice_stag.jks
    key-store-password: stagpassword
    key-store-type: JKS
    key-alias: authservice_stag
