spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db_dev?useSSL=false&serverTimezone=UTC
    username: root
    password: devpassword

server:
  ssl:
    enabled: true
    key-store: classpath:keystore/authservice_dev.jks
    key-store-password: devpassword
    key-store-type: JKS
    key-alias: authservice_dev
