spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:222.233.6.72}:${DATABASE_PORT:36191}/${DATABASE_NAME:local_forrrest_db}
    #?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DATABASE_USER:local_forrrest_user}
    password: ${DATABASE_USER:local_forrrest_password}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

logging:
  level:
    root: info
    com.forrrest: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: ${AUTH_PORT:8081}

