spring:
  profiles: deploy
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/auth_db?useSSL=false&serverTimezone=UTC
    username: root
    password: deploypassword

server:
  ssl:
    enabled: true
    key-store: classpath:keystore/authservice.jks
    key-store-password: deploypassword
    key-store-type: JKS
    key-alias: authservice
