spring:
  profiles:
    active: local

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

token:
#  secret: ${TOKEN_SECRET:c2VjcmV0a2V5Zm9yZGV2ZW52aXJvbm1lbnRzZWNyZXRrZXlmb3JkZXZlbnZpcm9ubWVudA==}
  keys: # key id 와 secret 을 담을 수 있는 구조만 정의
    key_v1:
      id: key_v1
      secret: ${TOKEN_KEY1_SECRET:c2VjcmV0a2V5Zm9yZGV2ZW52aXJvbm1lbnRzZWNyZXRrZXlmb3JkZXZlbnZpcm9ubWVudA==}
  current-key-id: key_v1
  validity:
    USER_ACCESS: 3600000        # 1시간
    USER_REFRESH: 604800000     # 7일
    PROFILE_ACCESS: 3600000     # 1시간
    PROFILE_REFRESH: 604800000  # 7일
    NONCE: 300000              # 5분

security:
  token:
    user-paths: /users, /profiles
    profile-paths: 
    nonce-paths:
    external-nonce-paths: #/nonce-tokens

logging:
  level:
    root: info
    com.forrrest: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8081