spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/auth_db?useSSL=false&serverTimezone=UTC
    username: root
    password: devpassword

server:
  ssl:
    enabled: true
    key-store: classpath:keystore/authservice_dev.jks
    key-store-password: devpassword
    key-store-type: JKS
    key-alias: authservice_dev
